version: "3"

services:
  aloha:
    image: "560730833886.dkr.ecr.ap-southeast-1.amazonaws.com/aloha-dev:latest"
    ports:
      - 5000:5000
    networks:
      - node-app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env.development

  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - node-app
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - node-app

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

networks:
  node-app:
    driver: bridge

volumes:
  mongo-data:
