version: "3"
services:
  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - aloha-platform
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - aloha-platform
  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - aloha-platform
  redis_commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'
    depends_on:
      - redis
    networks:
      - aloha-platform
networks:
  aloha-platform:
    driver: bridge

volumes:
  mongo-data:
